FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y \
        curl \
        rsync \
        python3 \
        python3-pip \
        python3-pyinotify \
        inotify-tools && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3 5

RUN apt-get install -y \
        nodejs \
        npm

ADD . /code
WORKDIR /code

RUN pip3 install -r backend/requirements.txt && \
    pip3 install inotify

CMD ["python", "scripts/watch_frontend.py"]
