FROM node:6.12

RUN apt-get update && \
    apt-get install -y \
        rsync \
        python3 \
        python3-pip \
        python3-pyinotify \
        inotify-tools \
        libmysqlclient-dev

ADD . /code
WORKDIR /code

RUN pip3 install --upgrade pip && \
    pip3 install -r backend/requirements.txt && \
    pip3 install inotify
CMD ["python3", "scripts/watch_frontend.py"]
