FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
        python3 \
        python3-pip

COPY backend/requirements.txt /code/requirements.txt
COPY settings.json /code/settings.json
RUN sed -i 's/"postgresHost"\s*:.*,/"postgresHost" : "db",/' /code/settings.json
WORKDIR /code

RUN pip3 install -r requirements.txt

CMD ["python3", "backend/route.py", "--develop"]
